import Documentation from "@/components/home/Documentation";
import SetupGuideInteractive from "../../components/common/SetupGuideInteractive";

export const metadata = {
    title: "Documentation",
    description: "Generated by create next app",
};

export default function DocumentationPage() {
  return (
    <div className="w-full p-8 flex flex-col items-center gap-8">
      <SetupGuideInteractive/>
      <Documentation />
    </div>
  );
}
