import { Suspense } from "react";
import Loader from "@/components/spinner/Loader";
import AuthCallback from "./components/AuthCallback";

export const metadata = {
  title: "Loading...",
  description: "Generated by create next app",
};

export default function Login() {
  return (
    <Suspense fallback={<Loader/>}>
        <AuthCallback/>
    </Suspense>
  )
}
