import Link from "next/link";
import LoginForm from "@/components/common/LoginForm";

export const metadata = {
    title: "Login",
    description: "Generated by create next app",
};

export default function Login() {
    return (
        <div className="flex justify-center items-center min-h-screen bg-gray-100">
            <div className="bg-white shadow-md rounded-lg p-8 w-96">
                <h2 className="text-2xl font-semibold text-gray-800 text-center">Login</h2>
                <p className="text-gray-500 text-center text-sm mt-2">
                    Don't have an account yet? <Link href="/signup" className="text-purple-600 font-medium">Sign Up</Link>
                </p>
 
                <LoginForm/>
            </div>
        </div>
    );
}
