import PublicFile from "@/components/common/PublicFile";

export const metadata = {
    title: "File",
    description: "Generated by create next app",
};

export default function publicFile() {
    return (
        <div className="w-full min-h-screen flex flex-col gap-4">
            <PublicFile/>
        </div>
    );
}