import FormMain from "@/components/dashboard/formDashboard/FormMain";

export const metadata = {
    title: "Dashboard - Form",
    description: "Generated by create next app",
};

export default function FormPage() {
    return (
        <div className="w-full min-h-screen flex flex-col gap-4">
            <FormMain/>
        </div>
    );
}