import Signup from "./components/Signup";

export const metadata = {
    title: "sign up",
    description: "Generated by create next app",
};

export default function signup(){
    return (
        <div className="flex justify-center items-center min-h-screen bg-gray-100">
            <div className="bg-white shadow-md rounded-lg p-8 w-96">
                <Signup/>
            </div>
        </div>
    )
}