import MainSetting from "@/components/dashboard/settings/MainSetting";

export const metadata = {
    title: "Dahboard - Settings",
    description: "Generated by create next app",
};

export default function settings(){
    return (
        <div className='w-full min-h-screen'>
            <MainSetting/>
        </div>
    )
}