import MainDashboard from "@/components/dashboard/MainDashboard";

export const metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default function dashboard(){
    return (
        <div className='w-full min-h-screen'>
            <MainDashboard/>
        </div>
    )
}