import { Suspense } from "react";
import ResetPassword from "./components/ResetPassword";
import Loader from "@/components/spinner/Loader";

export const metadata = {
  title: "Reset Password",
  description: "Generated by create next app",
};

export default function Login() {
  return (
    <Suspense fallback={<Loader/>}>
        <ResetPassword/>
    </Suspense>
  )
}
