import ResetPassword from "./components/ResetPassword";

export const metadata = {
    title: "Reset Password",
    description: "Generated by create next app",
};

export default function Login() {
    return (
        <ResetPassword/>
    );
}